@extends('layouts.public')
@section('title', 'Home')  
@section('content')
      @include('pages.partials.home.hero')
      @include('pages.partials.home.chi-siamo')
      @include('pages.partials.home.menu-section')
        @include('pages.partials.home.recensioni') 
        @include('pages.partials.home.contact') 
  @include('components.cookie-banner')
